import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/navbar';
import ReduxProvider from '@/providers/redux-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <ReduxProvider>
        <body className={inter.className}>
          <NavBar />
          <main className='min-h-screen max-w-screen-md w-full flex justify-center -mt-[60px] mx-auto'>
            {children}
          </main>
        </body>
      </ReduxProvider>
    </html>
  );
}
